name: shedule

on:
  workflow_dispatch:
  #schedule:
   # - cron: '*/5 * * * *'

jobs:
  build: # job_id
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo "Hello, world!"
