# GitHubActions запускает Python, который создает файл в репозиторий
name: realize

on:
  schedule:
    - cron: '14 */6 * * *'
   # workflow_dispatch:
  
jobs:
  build: # job_id
    runs-on: ubuntu-latest
    
    steps:
    #  - name: python check preset  # проверка версии python, предустановленой на вирт машине
    #    run: python --version  
      - name: repo checkout  # загрузка содержимого корня репозитория на вирт машину
        uses: actions/checkout@v4  
      - name: list current folder  # отобразить содержимое текущей директории (команда терминала Ubuntu)
        run: ls  
      - name: install PyGithub  # библиотека для работы с репозиторием GitHub
        run: pip install PyGithub
      - name: install beautifulsoup4  # библиотека для парсинга сайта (UEFA_club_coef_parse_TLstandings.py)
        run: pip install beautifulsoup4       
      - name: Run script  # выполнить файл на языке
        run: python UEFA_club_coef_parse_TLstandings.py
