name: Upload_Artefact

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: mkdir -p Outputs

      - run: echo hello > Outputs/world.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: Outputs/world.txt
